export type ConversationOperation =
	// TODO
	| 'addLabel'
	| 'create'
	// TODO
	| 'destroyCustomAttributes'
	| 'get'
	| 'list'
	// TODO
	| 'listMessages'
	| 'toggleStatus'
	| 'assignAgent'
	| 'assignTeam'
	| 'updateLabels'
	// TODO
	| 'removeLabel'
	// TODO
	| 'sendMessage'
	// TODO
	| 'sendFile'
	// TODO
	| 'setCustomAttributes'
	// TODO
	| 'setPriority'
	// TODO
	| 'updateLabels'
	// TODO
	| 'updateLastSeen'
	// TODO
	| 'updatePresence';
