export type ConversationOperation =
  | 'create'
  | 'get'
  | 'list'
  | 'sendMessage'
  | 'sendFile'
  | 'listMessages'
  | 'assignAgent'
  | 'assignTeam'
  | 'addLabels'
  | 'removeLabels'
  | 'updateLabels'
  | 'toggleStatus'
  | 'setPriority'
  | 'setCustomAttributes'
  | 'destroyCustomAttributes'
  | 'updateLastSeen'
  | 'updatePresence';
